name: BlueNotesBuild
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: 🛠️ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: 📦 Install MAUI Workload
        run: |
          dotnet workload install maui-android --source https://api.nuget.org/v3/index.json
          dotnet workload install android --source https://api.nuget.org/v3/index.json

      - name: 🔨 Build & Publish APK
        shell: pwsh
        run: |
          # Localiza o arquivo
          $projFile = Get-ChildItem -Filter *.csproj -Recurse | Select-Object -First 1 -ExpandProperty FullName
          
          # FORÇA O USO DO SDK E PUBLICA
          dotnet publish "$projFile" -f net9.0-android -c Release `
            -p:AndroidPackageFormat=apk `
            -p:AndroidKeyStore=false `
            -p:PublishAndroidPackage=true `
            --self-contained
            
      - name: 📤 Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: BlueNotes-APK-Final
          path: |
            **/bin/Release/net9.0-android/*.apk
          if-no-files-found: error
          
